### ISSUE TITLE
Support for the improved V1.1 model

### ISSUE THREAD

**Issue by ThatDocBoi** [kijai/ComfyUI-MimicMotionWrapper#22]
Hey, are there any plans to update it to support the 1.1 model that was released? 
Thanks!

**Comment by kijai** [comment]
It's supported now, but I'm not sure how to use it yet. The context length needs to be 72 for it to work properly, but that takes a lot of VRAM so resolution needs to be pretty low.

**Comment by JustinLion83** [comment]
wow... context length needs to be 72!! It's instane...how the difference is so big😂?!

**Comment by ThatDocBoi** [comment]
> It's supported now, but I'm not sure how to use it yet. The context length needs to be 72 for it to work properly, but that takes a lot of VRAM so resolution needs to be pretty low.

It looks like they just updated it to use less VRAM, it'd be great to have it merged whenever you have time. Thanks!

**Comment by JPW0080** [comment]
> It's supported now, but I'm not sure how to use it yet. The context length needs to be 72 for it to work properly, but that takes a lot of VRAM so resolution needs to be pretty low.

Without knowing the aforementioned, The current included workflow will give bad results.
