### ISSUE TITLE
Error occurred when executing DownloadAndLoadMimicMotionModel:

### ISSUE THREAD

**Issue by aimarxjg** [kijai/ComfyUI-MimicMotionWrapper#26]
'UNetSpatioTemporalConditionModel' object has no attribute 'pose_net'

File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 109, in loadmodel
set_module_tensor_to_device(self.unet, key, dtype=dtype, device=device, value=sd[key])
File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\utils\modeling.py", line 324, in set_module_tensor_to_device
new_module = getattr(module, split)
^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 151, in __getattr__
return super().__getattr__(name)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
======================================================
Problems after the update

**Comment by kijai** [comment]
It's trying to load the wrong model for some reason, the new model should be autodownloaded (I updated the old one too), the choices are these, check if you are selecting the new one:
![image](https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/40791699/62dc3d1e-b6ee-414d-8ac5-471facb807c5)

from:

https://huggingface.co/Kijai/MimicMotion_pruned/tree/main

**Comment by aimarxjg** [comment]
THX~THX ~THX

**Comment by lic9425** [comment]
> It's trying to load the wrong model for some reason, the new model should be autodownloaded (I updated the old one too), the choices are these, check if you are selecting the new one: ![image](https://private-user-images.githubusercontent.com/40791699/346611643-62dc3d1e-b6ee-414d-8ac5-471facb807c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTkyMTMsIm5iZiI6MTcyMDYxODkxMywicGF0aCI6Ii80MDc5MTY5OS8zNDY2MTE2NDMtNjJkYzNkMWUtYjZlZS00MTRkLThhYzUtNDcxZmFjYjgwN2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzNDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzODJmMjE0N2VlNjUzYjYzN2ZiOGQ3Y2JkMzdhYmYwNmI0ODIyMGNmYTRiZWE0ZWZjYmU4NWEwZmRmYjc4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2B2gIuFLxW3zEiOkwLumCosAYuGTyBaBEeJ78Mtmj2U)
> 
> from:
> 
> https://huggingface.co/Kijai/MimicMotion_pruned/tree/main

Mistakes happen no matter what you choose, right

**Comment by Luisellap** [comment]
Me too...
