### ISSUE TITLE
Error occurred when executing MimicMotionSampler:  list index out of range

### ISSUE THREAD

**Issue by Yukinoshita-Yukinoe** [kijai/ComfyUI-MimicMotionWrapper#3]
![31bfd6ba97e9811b72870c4934ee1715](https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/69832227/3399a1ff-f02f-49eb-8a04-83f50c4a8301)
How to solve it

**Comment by kijai** [comment]
That looks like old example workflow, I've updated it couple of times now, so I'd suggest updating and reloading the example.

**Comment by an-it-a** [comment]
Hi, I just cloned your project and the workflow, still see this error
