### ISSUE TITLE
Error: need at least one array to stack

### ISSUE THREAD

**Issue by an-it-a** [kijai/ComfyUI-MimicMotionWrapper#33]
Hi, how can I solve this error? Thanks!

<img width="1198" alt="Screenshot 2024-07-09 at 8 27 23 PM" src="https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/1251545/3a29b8c8-7c20-4625-9f3e-611c42b961d9">

**Comment by tdw-hyn** [comment]
me too!

**Comment by LesenlyMu** [comment]
too

**Comment by LesenlyMu** [comment]
这好像与视频有关，我选择40帧时可以正常使用，选择32帧时就会出现这个错误
![QQ截图20240715151430](https://github.com/user-attachments/assets/c1ed94c7-39cf-43a1-bf3e-dcee05198c75)

**Comment by EricoZhao** [comment]
我感觉是跟是否识别到骨骼有关系

**Comment by tigeyshark22** [comment]
Does this issue have anything to do with whether the body is recognized?
