### ISSUE TITLE
Pose detection results offset the screen

### ISSUE THREAD

**Issue by jiaqiAA** [kijai/ComfyUI-MimicMotionWrapper#85]
The actor should be in the middle of the frame, but it's shifted to the left. What is the reason?
![pose](https://github.com/user-attachments/assets/4e8ba381-d021-4430-8105-f6f8bbeb0295)

**Comment by kijai** [comment]
It attempts to align the pose of the reference and the guiding video, if they are too different weird stuff can happen.

**Comment by jiaqiAA** [comment]
but, In my test case, the pose of the reference and the firet frame of guiding video are the same.
